[2025-03-20T00:00:40.481+0000] {processor.py:186} INFO - Started process (PID=22240) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:00:40.498+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:00:40.513+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:00:40.513+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:00:41.029+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:00:41.018+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:00:41.034+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:00:41.099+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.665 seconds
[2025-03-20T00:01:18.554+0000] {processor.py:186} INFO - Started process (PID=22305) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:01:18.555+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:01:18.568+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:01:18.558+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:01:18.806+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:01:18.796+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:01:18.809+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:01:18.879+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.356 seconds
[2025-03-20T00:01:58.521+0000] {processor.py:186} INFO - Started process (PID=22380) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:01:58.533+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:01:58.536+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:01:58.536+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:01:58.761+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:01:58.692+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:01:58.764+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:01:58.828+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.330 seconds
[2025-03-20T00:02:36.736+0000] {processor.py:186} INFO - Started process (PID=22434) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:02:36.737+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:02:36.739+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:02:36.739+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:02:36.778+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:02:36.772+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:02:36.780+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:02:36.846+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.119 seconds
[2025-03-20T00:03:07.344+0000] {processor.py:186} INFO - Started process (PID=22503) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:03:07.345+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:03:07.346+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:03:07.346+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:03:07.364+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:03:07.360+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:03:07.366+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:03:07.390+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.053 seconds
[2025-03-20T00:03:37.684+0000] {processor.py:186} INFO - Started process (PID=22572) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:03:37.685+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:03:37.686+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:03:37.686+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:03:37.705+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:03:37.701+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:03:37.707+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:03:37.727+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.050 seconds
[2025-03-20T00:04:09.823+0000] {processor.py:186} INFO - Started process (PID=22640) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:04:09.825+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:04:09.827+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:04:09.827+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:04:09.882+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:04:09.874+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:04:09.885+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:04:09.963+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.160 seconds
[2025-03-20T00:04:41.107+0000] {processor.py:186} INFO - Started process (PID=22709) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:04:41.108+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:04:41.110+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:04:41.110+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:04:41.149+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:04:41.136+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:04:41.153+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:04:41.200+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.104 seconds
[2025-03-20T00:05:13.522+0000] {processor.py:186} INFO - Started process (PID=22777) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:05:13.527+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:05:13.529+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:05:13.529+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:05:13.665+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:05:13.659+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:05:13.668+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:05:13.741+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.252 seconds
[2025-03-20T00:05:44.656+0000] {processor.py:186} INFO - Started process (PID=22845) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:05:44.658+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:05:44.661+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:05:44.660+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:05:44.687+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:05:44.679+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:05:44.689+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:05:44.740+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.097 seconds
[2025-03-20T00:06:16.966+0000] {processor.py:186} INFO - Started process (PID=22914) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:06:16.984+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:06:17.007+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:06:17.006+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:06:17.078+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:06:17.073+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:06:17.080+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:06:17.113+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.175 seconds
[2025-03-20T00:06:49.211+0000] {processor.py:186} INFO - Started process (PID=22981) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:06:49.353+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:06:49.374+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:06:49.374+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:06:49.824+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:06:49.740+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:06:49.833+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:06:49.939+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.774 seconds
[2025-03-20T00:07:20.731+0000] {processor.py:186} INFO - Started process (PID=23050) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:07:20.732+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:07:20.734+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:07:20.734+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:07:20.761+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:07:20.754+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:07:20.769+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:07:20.800+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.085 seconds
[2025-03-20T00:07:51.499+0000] {processor.py:186} INFO - Started process (PID=23119) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:07:51.501+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:07:51.505+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:07:51.503+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:07:51.522+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:07:51.518+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:07:51.524+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:07:51.567+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.078 seconds
[2025-03-20T00:08:26.047+0000] {processor.py:186} INFO - Started process (PID=23193) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:08:26.061+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:08:26.086+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:08:26.084+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:08:26.904+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:08:26.708+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:08:26.982+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:08:27.094+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 1.291 seconds
[2025-03-20T00:08:57.883+0000] {processor.py:186} INFO - Started process (PID=23262) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:08:57.884+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:08:57.887+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:08:57.886+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:08:57.916+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:08:57.909+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:08:57.919+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:08:58.023+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.150 seconds
[2025-03-20T00:09:34.284+0000] {processor.py:186} INFO - Started process (PID=23331) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:09:34.319+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:09:34.389+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:09:34.388+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:09:34.722+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:09:34.696+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:09:34.739+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:09:34.912+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.665 seconds
[2025-03-20T00:10:06.639+0000] {processor.py:186} INFO - Started process (PID=23400) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:10:06.644+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:10:06.647+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:10:06.646+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:10:06.715+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:10:06.703+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:10:06.719+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:10:06.861+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.238 seconds
[2025-03-20T00:10:37.091+0000] {processor.py:186} INFO - Started process (PID=23468) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:10:37.095+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:10:37.100+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:10:37.098+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:10:37.134+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:10:37.123+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:10:37.136+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:10:37.190+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.124 seconds
[2025-03-20T00:11:07.338+0000] {processor.py:186} INFO - Started process (PID=23535) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:11:07.341+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:11:07.345+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:11:07.344+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:11:07.368+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:11:07.364+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:11:07.370+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:11:07.399+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.073 seconds
[2025-03-20T00:11:39.680+0000] {processor.py:186} INFO - Started process (PID=23603) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:11:39.684+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:11:39.687+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:11:39.686+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:11:39.790+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:11:39.782+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:11:39.792+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:11:39.830+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.166 seconds
[2025-03-20T00:12:14.619+0000] {processor.py:186} INFO - Started process (PID=23670) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:12:14.641+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:12:14.644+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:12:14.643+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:12:14.938+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:12:14.928+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:12:14.989+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:12:15.151+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.556 seconds
[2025-03-20T00:12:46.238+0000] {processor.py:186} INFO - Started process (PID=23739) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:12:46.249+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:12:46.255+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:12:46.254+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:12:46.414+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:12:46.381+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:12:46.416+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:12:46.466+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.250 seconds
[2025-03-20T00:13:17.145+0000] {processor.py:186} INFO - Started process (PID=23807) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:13:17.146+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:13:17.148+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:13:17.148+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:13:17.167+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:13:17.163+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:13:17.169+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:13:17.201+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.063 seconds
[2025-03-20T00:13:53.538+0000] {processor.py:186} INFO - Started process (PID=23876) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:13:53.552+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:13:53.556+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:13:53.556+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:13:53.698+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:13:53.678+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:13:53.700+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:13:53.752+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.251 seconds
[2025-03-20T00:14:23.901+0000] {processor.py:186} INFO - Started process (PID=23945) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:14:23.904+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:14:23.907+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:14:23.906+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:14:23.940+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:14:23.933+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:14:23.943+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:14:24.023+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.141 seconds
[2025-03-20T00:14:58.360+0000] {processor.py:186} INFO - Started process (PID=24011) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:14:58.391+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:14:58.409+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:14:58.409+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:14:58.459+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:14:58.445+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:14:58.461+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:14:58.523+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.188 seconds
[2025-03-20T00:15:43.431+0000] {processor.py:186} INFO - Started process (PID=24079) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:15:43.594+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:15:43.682+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:15:43.682+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:15:49.541+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:15:48.665+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:15:49.745+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:15:49.879+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 6.467 seconds
[2025-03-20T00:16:30.189+0000] {processor.py:186} INFO - Started process (PID=24146) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:16:30.191+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:16:30.193+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:16:30.192+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:16:30.233+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:16:30.227+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:16:30.236+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:16:30.308+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.132 seconds
[2025-03-20T00:17:07.253+0000] {processor.py:186} INFO - Started process (PID=24215) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:17:07.255+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:17:07.265+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:17:07.264+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:17:07.308+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:17:07.301+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:17:07.311+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:17:07.409+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.170 seconds
[2025-03-20T00:17:40.639+0000] {processor.py:186} INFO - Started process (PID=24284) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:17:40.640+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:17:40.643+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:17:40.642+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:17:40.679+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:17:40.673+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:17:40.682+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:17:40.733+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.115 seconds
[2025-03-20T00:18:18.721+0000] {processor.py:186} INFO - Started process (PID=24345) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:18:18.734+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:18:18.741+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:18:18.740+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:18:18.920+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:18:18.904+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:18:18.923+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:18:18.991+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.339 seconds
[2025-03-20T00:18:53.412+0000] {processor.py:186} INFO - Started process (PID=24418) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:18:53.415+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:18:53.418+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:18:53.418+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:18:53.490+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:18:53.477+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:18:53.493+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:18:53.536+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.138 seconds
[2025-03-20T00:19:25.160+0000] {processor.py:186} INFO - Started process (PID=24485) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:19:25.161+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:19:25.170+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:19:25.169+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:19:25.312+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:19:25.280+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:19:25.316+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:19:25.412+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.263 seconds
[2025-03-20T00:19:57.441+0000] {processor.py:186} INFO - Started process (PID=24554) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:19:57.452+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:19:57.455+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:19:57.455+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:19:57.507+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:19:57.502+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:19:57.521+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:19:57.630+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.240 seconds
[2025-03-20T00:20:31.389+0000] {processor.py:186} INFO - Started process (PID=24623) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:20:31.394+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:20:31.404+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:20:31.403+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:20:31.558+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:20:31.552+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:20:31.560+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:20:31.634+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.273 seconds
[2025-03-20T00:21:02.117+0000] {processor.py:186} INFO - Started process (PID=24691) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:21:02.125+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:21:02.132+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:21:02.131+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:21:02.174+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:21:02.166+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:21:02.226+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:21:02.304+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.206 seconds
[2025-03-20T00:21:35.567+0000] {processor.py:186} INFO - Started process (PID=24759) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:21:35.568+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:21:35.571+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:21:35.570+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:21:35.622+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:21:35.615+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:21:35.625+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:21:35.669+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.111 seconds
[2025-03-20T00:22:08.167+0000] {processor.py:186} INFO - Started process (PID=24822) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:22:08.169+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:22:08.181+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:22:08.179+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:22:08.488+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:22:08.472+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:22:08.501+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:22:08.581+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.471 seconds
[2025-03-20T00:22:39.044+0000] {processor.py:186} INFO - Started process (PID=24892) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:22:39.046+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:22:39.048+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:22:39.048+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:22:39.085+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:22:39.078+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:22:39.090+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:22:39.132+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.100 seconds
[2025-03-20T00:23:09.740+0000] {processor.py:186} INFO - Started process (PID=24960) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:23:09.742+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:23:09.745+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:23:09.744+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:23:09.964+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:23:09.959+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:23:09.966+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:23:10.013+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.293 seconds
[2025-03-20T00:23:48.867+0000] {processor.py:186} INFO - Started process (PID=25029) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:23:48.869+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:23:48.872+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:23:48.871+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:23:49.035+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:23:49.023+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:23:49.038+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:23:49.192+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.356 seconds
[2025-03-20T00:24:19.353+0000] {processor.py:186} INFO - Started process (PID=25098) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:24:19.354+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:24:19.357+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:24:19.357+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:24:19.377+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:24:19.373+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:24:19.378+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:24:19.396+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.054 seconds
[2025-03-20T00:24:49.900+0000] {processor.py:186} INFO - Started process (PID=25163) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:24:49.901+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:24:49.903+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:24:49.902+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:24:49.922+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:24:49.918+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:24:49.923+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:24:49.957+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.074 seconds
[2025-03-20T00:25:20.513+0000] {processor.py:186} INFO - Started process (PID=25232) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:25:20.515+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:25:20.517+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:25:20.517+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:25:20.584+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:25:20.547+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:25:20.630+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:25:20.788+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.295 seconds
[2025-03-20T00:25:52.423+0000] {processor.py:186} INFO - Started process (PID=25305) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:25:52.435+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:25:52.443+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:25:52.441+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:25:52.513+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:25:52.507+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:25:52.515+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:25:52.554+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.169 seconds
[2025-03-20T00:26:23.098+0000] {processor.py:186} INFO - Started process (PID=25373) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:26:23.100+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:26:23.102+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:26:23.101+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:26:23.136+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:26:23.127+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:26:23.138+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:26:23.176+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.093 seconds
[2025-03-20T00:26:53.552+0000] {processor.py:186} INFO - Started process (PID=25442) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:26:53.554+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:26:53.558+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:26:53.557+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:26:53.634+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:26:53.590+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:26:53.641+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:26:53.730+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.197 seconds
[2025-03-20T00:27:23.978+0000] {processor.py:186} INFO - Started process (PID=25509) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:27:23.979+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:27:23.981+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:27:23.980+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:27:24.004+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:27:23.999+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:27:24.007+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:27:24.045+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.076 seconds
[2025-03-20T00:27:54.981+0000] {processor.py:186} INFO - Started process (PID=25572) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:27:54.983+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:27:54.989+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:27:54.988+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:27:55.109+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:27:55.103+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:27:55.111+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:27:55.157+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.186 seconds
[2025-03-20T00:28:25.607+0000] {processor.py:186} INFO - Started process (PID=25640) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:28:25.609+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:28:25.611+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:28:25.611+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:28:25.633+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:28:25.628+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:28:25.635+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:28:25.676+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.079 seconds
[2025-03-20T00:28:55.819+0000] {processor.py:186} INFO - Started process (PID=25709) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:28:55.821+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:28:55.824+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:28:55.823+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:28:55.911+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:28:55.862+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:28:55.914+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:28:56.015+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.205 seconds
[2025-03-20T00:29:26.334+0000] {processor.py:186} INFO - Started process (PID=25778) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:29:26.335+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:29:26.337+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:29:26.336+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:29:26.377+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:29:26.370+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:29:26.380+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:29:26.430+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.108 seconds
[2025-03-20T00:29:57.101+0000] {processor.py:186} INFO - Started process (PID=25844) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:29:57.103+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:29:57.107+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:29:57.106+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:29:57.129+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:29:57.125+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:29:57.131+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:29:57.167+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.080 seconds
[2025-03-20T00:30:27.638+0000] {processor.py:186} INFO - Started process (PID=25912) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:30:27.639+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:30:27.643+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:30:27.642+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:30:27.680+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:30:27.673+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:30:27.683+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:30:27.735+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.109 seconds
[2025-03-20T00:30:59.034+0000] {processor.py:186} INFO - Started process (PID=25981) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:30:59.036+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:30:59.040+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:30:59.039+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:30:59.121+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:30:59.115+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:30:59.123+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:30:59.275+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.256 seconds
[2025-03-20T00:31:30.129+0000] {processor.py:186} INFO - Started process (PID=26050) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:31:30.131+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:31:30.133+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:31:30.133+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:31:30.169+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:31:30.160+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:31:30.173+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:31:30.225+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.107 seconds
[2025-03-20T00:32:02.620+0000] {processor.py:186} INFO - Started process (PID=26115) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:32:02.622+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:32:02.624+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:32:02.623+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:32:02.648+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:32:02.643+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:32:02.650+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:32:02.691+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.092 seconds
[2025-03-20T00:32:33.915+0000] {processor.py:186} INFO - Started process (PID=26183) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:32:33.918+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:32:33.922+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:32:33.920+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:32:33.959+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:32:33.952+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:32:33.961+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:32:34.037+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.135 seconds
[2025-03-20T00:33:06.440+0000] {processor.py:186} INFO - Started process (PID=26245) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:33:06.445+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:33:06.448+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:33:06.447+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:33:06.592+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:33:06.507+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:33:06.624+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:33:06.740+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.312 seconds
[2025-03-20T00:33:40.755+0000] {processor.py:186} INFO - Started process (PID=26309) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:33:40.757+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:33:40.761+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:33:40.760+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:33:40.796+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:33:40.787+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:33:40.799+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:33:40.860+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.119 seconds
[2025-03-20T00:34:13.158+0000] {processor.py:186} INFO - Started process (PID=26378) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:34:13.161+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:34:13.173+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:34:13.163+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:34:14.328+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:34:14.105+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:34:14.348+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:34:14.466+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 1.329 seconds
[2025-03-20T00:34:44.598+0000] {processor.py:186} INFO - Started process (PID=26446) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:34:44.600+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:34:44.601+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:34:44.601+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:34:44.630+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:34:44.619+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:34:44.632+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:34:44.674+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.086 seconds
[2025-03-20T00:35:15.199+0000] {processor.py:186} INFO - Started process (PID=26514) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:35:15.201+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:35:15.203+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:35:15.202+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:35:15.230+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:35:15.224+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:35:15.232+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:35:15.272+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.092 seconds
[2025-03-20T00:35:46.118+0000] {processor.py:186} INFO - Started process (PID=26583) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:35:46.119+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:35:46.122+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:35:46.121+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:35:46.148+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:35:46.142+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:35:46.151+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:35:46.241+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.150 seconds
[2025-03-20T00:36:19.501+0000] {processor.py:186} INFO - Started process (PID=26658) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:36:19.514+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:36:19.532+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:36:19.531+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:36:20.949+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:36:20.050+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:36:21.382+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:36:21.781+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 2.315 seconds
[2025-03-20T00:36:51.976+0000] {processor.py:186} INFO - Started process (PID=26729) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:36:51.979+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:36:51.982+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:36:51.981+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:36:52.074+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:36:52.032+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:36:52.080+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:36:52.128+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.164 seconds
[2025-03-20T00:37:24.572+0000] {processor.py:186} INFO - Started process (PID=26797) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:37:24.577+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:37:24.583+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:37:24.583+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:37:24.629+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:37:24.617+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:37:24.633+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:37:24.704+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.199 seconds
[2025-03-20T00:37:55.129+0000] {processor.py:186} INFO - Started process (PID=26866) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:37:55.132+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:37:55.135+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:37:55.134+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:37:55.172+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:37:55.164+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:37:55.174+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:37:55.272+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.158 seconds
[2025-03-20T00:38:25.384+0000] {processor.py:186} INFO - Started process (PID=26932) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:38:25.390+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:38:25.393+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:38:25.392+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:38:25.423+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:38:25.415+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:38:25.425+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:38:25.484+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.113 seconds
[2025-03-20T00:38:56.612+0000] {processor.py:186} INFO - Started process (PID=27001) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:38:56.641+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:38:56.643+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:38:56.642+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:38:56.790+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:38:56.776+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:38:56.792+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:38:56.905+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.315 seconds
[2025-03-20T00:39:35.780+0000] {processor.py:186} INFO - Started process (PID=27069) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:39:35.816+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:39:35.826+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:39:35.826+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:39:36.049+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:39:36.042+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:39:36.051+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:39:36.180+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.416 seconds
[2025-03-20T00:40:06.944+0000] {processor.py:186} INFO - Started process (PID=27136) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:40:06.955+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:40:06.960+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:40:06.959+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:40:07.013+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:40:07.006+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:40:07.016+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:40:07.307+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.383 seconds
[2025-03-20T00:40:38.102+0000] {processor.py:186} INFO - Started process (PID=27204) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:40:38.103+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:40:38.106+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:40:38.106+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:40:38.264+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:40:38.254+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:40:38.266+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:40:38.466+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.389 seconds
[2025-03-20T00:41:08.849+0000] {processor.py:186} INFO - Started process (PID=27273) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:41:08.663+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:41:08.668+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:41:08.667+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:41:08.736+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:41:08.722+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:41:08.742+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:41:08.789+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.177 seconds
[2025-03-20T00:41:39.163+0000] {processor.py:186} INFO - Started process (PID=27340) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:41:39.165+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:41:39.169+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:41:39.169+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:41:39.335+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:41:39.302+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:41:39.350+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:41:39.426+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.276 seconds
[2025-03-20T00:42:11.336+0000] {processor.py:186} INFO - Started process (PID=27407) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:42:11.341+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:42:11.344+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:42:11.343+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:42:11.455+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:42:11.448+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:42:11.462+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:42:11.513+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.192 seconds
[2025-03-20T00:42:43.583+0000] {processor.py:186} INFO - Started process (PID=27477) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:42:43.585+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:42:43.588+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:42:43.587+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:42:43.621+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:42:43.615+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:42:43.624+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:42:43.707+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.156 seconds
[2025-03-20T00:43:14.882+0000] {processor.py:186} INFO - Started process (PID=27535) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:43:14.885+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:43:14.888+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:43:14.887+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:43:14.933+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:43:14.926+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:43:14.938+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:43:14.983+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.130 seconds
[2025-03-20T00:43:49.409+0000] {processor.py:186} INFO - Started process (PID=27596) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:43:49.413+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:43:49.425+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:43:49.418+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:43:49.457+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:43:49.452+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:43:49.460+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:43:49.487+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.112 seconds
[2025-03-20T00:44:19.565+0000] {processor.py:186} INFO - Started process (PID=27663) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:44:19.572+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:44:19.574+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:44:19.574+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:44:19.640+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:44:19.622+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:44:19.694+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:44:19.761+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.212 seconds
[2025-03-20T00:44:51.617+0000] {processor.py:186} INFO - Started process (PID=27731) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:44:51.621+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:44:51.630+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:44:51.629+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:44:51.778+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:44:51.773+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:44:51.780+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:44:51.884+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.313 seconds
[2025-03-20T00:45:27.638+0000] {processor.py:186} INFO - Started process (PID=27799) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:45:27.640+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:45:27.652+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:45:27.651+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:45:27.961+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:45:27.910+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:45:28.009+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:45:28.136+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.519 seconds
[2025-03-20T00:45:59.108+0000] {processor.py:186} INFO - Started process (PID=27868) to work on /opt/airflow/dags/dbt.py
[2025-03-20T00:45:59.110+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dbt.py for tasks to queue
[2025-03-20T00:45:59.120+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:45:59.119+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dbt.py
[2025-03-20T00:45:59.161+0000] {logging_mixin.py:190} INFO - [2025-03-20T00:45:59.154+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt.py", line 4, in <module>
    from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
ModuleNotFoundError: No module named 'cosmos'
[2025-03-20T00:45:59.178+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt.py
[2025-03-20T00:45:59.269+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dbt.py took 0.182 seconds
